#Check Player Arena Addon for MBedwars by dejwideek

#Hex color: <SOLID:(hex without #)>
#Example: "<SOLID:fdfdfd>hex color"

#Hex gradient color:
#- start variable: <GRADIENT:(hex without #)>
#- end variable: </GRADIENT:(hex without #)>
#Example: "<GRADIENT:000000>gradient</GRADIENT:ffffff>"

#Hex rainbow color:
#- start variable: <RAINBOW(saturation value)>
#- end variable: </RAINBOW>
#Smaller value: darker
#Higher value: brighter
#Example: "<RAINBOW1>rainbow</RAINBOW>"

#This features works only on 1.16+ version

#Don't change this!
config-version: 1

#Permissions
Permissions:
  Check: "bw.checkplayerarena"
  Reload: "bw.checkplayerarena.reload"

#Messages
Messages:
  Usage: "&cUsage: /checkarena <player>"
  Not-Found: "&cThis player isn't online!"
  No-Inside-Arena: "&cThis player isn't playing!"

  #Available placeholder: %permission%
  No-Permission: "&cYou must have permission &4%permission% &cto do this!"

  #Available placeholders: %player%, %arena%
  Arena-Info: "&6%player% &eis playing on &c%arena%"

  Reloaded: "&eSuccessfully reloaded configuration file!"